package com.prachi.Entity;
import java.time.LocalDate;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
@Data
@AllArgsConstructor
@NoArgsConstructor

@Entity
public class Product 
{
	
@Id
@GeneratedValue(strategy=GenerationType.IDENTITY)
Long id;          // value will be automatically generated by db
String name;
String description;
double price;
int quantity;
String category;
String brand;
LocalDate createDate;
LocalDate updateDate;

}